# Generated by Django 5.0.6 on 2024-06-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_rename_end_time_event_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
