# Generated by Django 5.0.6 on 2024-06-27 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_person_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scheduler.person'),
        ),
    ]
